

/*===============================================*/
/* STORED PROCEDURES							 */
/*===============================================*/

USE carrentaldb;
GO


/*
SP INPUT : CUSTOMER EMAIL , RENTAL ID
SP OUTPUT: NO OUTPUT
SP WORK  : INITAITING A CUSTOMER REFUND REQUEST
*/
GO
CREATE PROC spInitRequest
	@RID	int, 
	@CEMAIL Varchar(256)
AS
	DECLARE @CID int, @RD datetime
	SET @CID = (SELECT CT_ID FROM TBLCUSTOMER WHERE CT_EMAIL = @CEMAIL)
	SET @RD = (SELECT GETDATE())
	INSERT INTO TBLREQUEST (REQ_RI_RENT_ID, REQ_CT_ID, REQ_STATUS, REQ_DATE)
	VALUES
	(@RID, @CID, 0, @RD);
GO

/*
SP INPUT : NB OF DAYS WANT TO RENT, CUSTOMER EMAIL , CAR ID
SP OUTPUT: NO OUTPUT
SP WORK  : RENT SPECIFIC CAR
*/
GO
CREATE PROC spRentCar
	@CARID	int,
	@DAYS	int,
	@CEMAIL	Varchar(256)
AS
	DECLARE	@CID		int,
			@Date		datetime,
			@Adue		datetime,
			@Total		float
	SET @CID = (SELECT CT_ID FROM TBLCUSTOMER WHERE CT_EMAIL = @CEMAIL)
	SET @Date = (SELECT GETDATE())
	SET @Adue = (DATEADD(DAY, @DAYS, @Date))
	SET @Total = ( (SELECT CAR_PRICE_PER_DAY FROM TBLCAR WHERE CAR_ID = @CARID) * @DAYS)
GO


/*
SP INPUT : REQUEST ID
SP OUTPUT: NO OUTPUT
SP WORK  : DELETE ROW SPECIFIED BY REQUEST FROM REQUEST TABLE
*/
GO
CREATE PROC spDeleteRequest
	@RentId	int
AS
	DELETE FROM TBLREQUEST WHERE REQ_RI_RENT_ID = @RentId
GO
